### ISSUE TITLE
Fail decoding with "Invalid payload length"

### ISSUE THREAD

**Issue by yutkin** [xiph/opus#152]
I'm trying to decode [this](https://psv4.userapi.com/c852336//u302747398/audiomsg/d18/b58ccbc2f7.ogg) OpusOgg file using `./opus_demo -d 48000 1 b58ccbc2f7.ogg new.wav`, but get `Invalid payload length: 1332176723` error. At the same time, `opusdec` utility decodes this file normally.

What am I doing wrong when I use `opus_demo`? I need to decode such files in C++, but stuck on this example.

**Comment by mark4o** [comment]
opus_demo does not read or write Ogg Opus files.  By default (without -e or -d) it simply encodes a packet and then immediately decodes it, and checks that the final range matches in the encoder and decoder, in order to test the encoder and decoder.  With the -e option it will only encode, writing each packet and final range to a file, and with the -d option it will only decode and check the final range, reading the format written by -e.  These files are not in a standard format and are not intended to be used by other programs.  To read standard Ogg Opus files, use opusdec from the opus-tools package or the opusfile library.

**Comment by qusc** [comment]
In case this helpful to anyone struggling with reading opus frames using the `opus_demo` executable: it expects big-endian 32-bit length-prefixed packets in the input file.
