### ISSUE TITLE
s/decoded/encoded in OPUS_GET_LAST_PACKET_DURATION doc

### ISSUE THREAD

**Issue by ryanhaining** [xiph/opus#2]
I could be wrong, but in the encoder-specific-ctls I see OPUS_GET_LAST_PACKET_DURATION documented with reference to the number of packets *decoded* instead of encoded:

*Gets the duration (in samples) of the last packet successfully **decoded** or concealed*

afaik the encoder isn't aware of a decoder so this seems like a typo to me.

https://github.com/xiph/opus/blob/699b64304299009e14a7ca5ea4ffd308e2e552dc/include/opus_defines.h#L699

**Comment by mark4o** [comment]
This is a decoder CTL, used only with a decoder.

You are probably looking at the documentation for the 1.1 release, which was fixed in f5a351a3.  It is now correctly under "Decoder related CTLs" (see line 677), and ends up correctly in the Decoder related CTLs documentation (https://mf4.xiph.org/jenkins/view/opus/job/opus/ws/doc/html/group__opus__decoderctls.html), and not in the Encoder related CTLs (https://mf4.xiph.org/jenkins/view/opus/job/opus/ws/doc/html/group__opus__encoderctls.html).

**Comment by ryanhaining** [comment]
Yes thanks, I was looking at: http://www.opus-codec.org/docs/html_api-1.1.0/group__opus__encoderctls.html#ga8f3d070f56b75f2a7af54e5776b387fa
