### ISSUE TITLE
ffmpeg libopus producing larger file size for the same bitrate as compared to vorbis

### ISSUE THREAD

**Issue by manujchandra** [xiph/opus#263]
I am using ffmpeg version 4.4.2

I collected a flac, mp3, wav and aac in a folder. The total size of the folder was around 76MB

Then I converted all of them to vorbis:
`ffmpeg -i <input> -c:a libvorbis -b:a 128k -vn -vbr on <output>`
The total size of all the files after conversion was ~13MB

Then I converted all of them to opus:
`ffmpeg -i <input> -c:a libopus -b:a 128k -vn -vbr on <output>`
The total size of all the files after conversion was ~15MB

I was wondering why libopus is producing a larger file size as compared to vorbis because as per my understanding the file size of opus should be approximately equal to vorbis.

Thanks.

P.S:
I am attaching a sample of some royalty free music:

[Sample.zip](https://github.com/xiph/opus/files/9751096/Sample.zip)

As can be seen the opus file size is larger in the sample also.

**Comment by silverbacknet** [comment]
It's better to think of "bitrate" in Opus and Vorbis as a quality factor, rather than a hard-and-fast rate. Like a much more fine-tunable version of LAME's Vx presets, except that the values for Xiph's bitrates actually *do* average out over a wide variety of content near the given bitrate. Finding any single piece of audio where they hit it on the nose is rare. Vorbis and Opus have very different methods of transforming audio, and somewhat different "easy" and "hard" areas, so it makes sense that they aren't entirely related in bitrate decisions on any individual song either.

As most of my music library is electronic and dance music, I just automatically accept that it'll always be 5-10% higher than the nominal bitrate, as that's what it takes to sound as good as, say, a folk song or a bass solo from Geddy Lee at far under the nominal bitrate. Vorbis tended to have even wider ranges in my experience.

There is a cbr mode to Opus, but now it's quality that will be uneven, rather than bitrate.

**Comment by manujchandra** [comment]
Thanks for your response.

Curiously, when I did a comparison in Handbrake, with identical profiles but one using vorbis and in the other using opus, I saw a reduction in opus test, although it was not significant.

I read that opus produces smaller or equal sized audio, but in my tests using FFmpeg I am getting a bigger opus across the board.

I also noticed that opus was using 48K, but vorbis was using 44k. Maybe this has something to do with the size? I lowered sampling rate for opus to 16k(if I remember correctly), but still the file size was not lower than vorbis 44k.

**Comment by manujchandra** [comment]
@silverbacknet 

Hi Emily,

The use case is that I have some audio files which I want to archive on a cloud bucket. Theoretically, the smaller the size the lesser the bill. This is the reason I was conducting tests to get equivalent quality to vorbis at an equal or lower size.

I took 4 audio files - one flac, wav, mp3 and aac. I encoded them using the above commands, but changed the bit rate. These are the results I got:

Original Size : 50.7 MB
| Codec  | kbps | size in MB |
|--------|------|------------|
| vorbis | 128  | 9.84       |
| opus   | 64   | 5.68       |
| opus   | 100  | 8.62       |
| opus   | 112  | 9.52       |
| opus   | 128  | 11         |

I think opus at 112kbps is giving approximately the same size as vorbis at 128. The question is that is the quality equivalent? Personally, I could not tell the difference in this small sample.

> Is Opus being 10% larger for your small sample set really enough of a dealbreaker to keep trying to break the codec until you can get them equal?

I guess not. I read that opus produces smaller files than vorbis, so I was investigating why I am getting larger files out of curiosity.

**Comment by manujchandra** [comment]
I think I am going to stick to the recommended bitrates:

https://wiki.xiph.org/Opus_Recommended_Settings#Recommended_Bitrates
