### ISSUE TITLE
Warble in LF with sample at 192kbps

### ISSUE THREAD

**Issue by tdaede** [xiph/opus#29]
original: https://people.xiph.org/~tdaede/Xte.flac
64kbps: https://people.xiph.org/~tdaede/Xt_.opus
192kbps: https://people.xiph.org/~tdaede/Xt2.opus

I am personally unable to ABX this.

**Comment by haasn** [comment]
I can ABX it very readily at 64kbps. It's less obvious in the 192kbps version but still present.

I just turned off my speakers and listened to only the sub. The effect kicks in right at the beginning, the first 3 seconds are enough. Rather than the bass being smooth and continuous, it sounds like it stutters.

**Comment by tdaede** [comment]
I think this is due to the 180 degree stereo. I'm surprised it's being used at 192kbps. The sub mixes the channels together and causes cancellation.

**Comment by tdaede** [comment]
IS isn't used on the LF bands (and especially not at 192kbps) so disregard my previous comment.

**Comment by jmvalin** [comment]
Seems to be due to extreme energy in LF and the leakage it causes in the next few bands.

**Comment by jmvalin** [comment]
The issue should be fixed in https://git.xiph.org/?p=opus.git;a=commitdiff;h=0cc4d9659aaa3
Feedback welcome.

**Comment by jmvalin** [comment]
I'm assuming it's working. Feel free to reopen if it's still a problem.
