### ISSUE TITLE
Add Support for 44.1 kHz

### ISSUE THREAD

**Issue by GregSlazinski** [xiph/opus#43]
I'm a passionate music listener, and a game developer, so I deal with a lot of music and sound files.
99.9% of the content that I encountered in my life is in 44.1 kHz sampling rate, but Opus does not support that. I'm really concerned about the resampling.

From the documentation https://wiki.xiph.org/OpusFAQ#But_won.27t_the_resampler_hurt_the_quality.3F_Isn.27t_it_better_to_use_44.1_kHz_directly.3F
> The Opus encoder is heavily tuned for 48 kHz now and using it at 44.1 kHz will cause it to make sub-optimal decisions.

Isn't the better solution, is to add a special mode for the 44.1, and tune that mode the same way as 48 is tuned?
Because right now when trying to use Opus with 44.1, we have resampling + lossy compression on top of that. So 2 lossy operations.
If you would provide a tuned version of the encoder for 44.1 mode, then we would have only one lossy operation, which is the encoding, without having to do resampling. I think that would be the best solution.

I strongly believe that if you would add native support for 44.1 sampling rate, then Opus would become much more popular. Because, like I said at the start, at least in my experience, 44.1 is the 99.9% of the audio content flying on the internet, and because of the resampling needed, Opus doesn't seem like a perfect solution, for which I'm still sticking with Vorbis.

**Comment by rillian** [comment]
A mode tuned for 44.1 kHz (pretending it's actually 48 kHz) could be added, but it would be a lot of work without benefit. You needn't be concerned about resampling. There are many transparent (without audible artefacts) resamplers which will do a fine job converting 44.1 kHz input to 48 kHz for encoding in Opus.

Put another way, if you have an application where resampling causes quality loss, you should use a lossless compressor like FLAC instead of Opus.

**Comment by gcp** [comment]
>I'm really concerned about the resampling...So 2 lossy operations....for which I'm still sticking with Vorbis.

The losses introduced by resampling are below audible thresholds. The whole workings of a lossy codec are a stack of lossy operations! Why focus on the one that has about the least loss of all of them? You're worrying about it in Opus, when in reality the quality loss due to it is far below the quality loss you get from Vorbis('s stack of lossy operations) as compared to Opus's.

Opus gives better quality at 44.1kHz than Vorbis does. And Opus *does* support 44.1kHz, unlike the bug title implies. Using a resampler doesn't mean it's not supported, on the contrary.

**Comment by jmvalin** [comment]
From a compatibility perspective, a 44.1 kHz Opus would be like a new codec and it would be incompatible with existing deployment. Breaking compatibility because of a thought experiment (assuming that resampling degrades quality despite no evidence existing) is not something we're going to do.

**Comment by Ultragod** [comment]
The opus codec is absolute garbage because it sounds VERY harsh, even worse than AAC, which sounds absolute krap compared 2 OOG, which sounds worse than MP3.  If U R not deaf, the additional harshness is extremely easy 2 hear & very obvious & annoying on music with lots of high frequency content.  In the same way that OOG sounds better than AAC for downloading youtube videos, Opus is a plauge that wrecks sound quality wherever it goes, with the aliasing distortions & other breaking glass texture that destroys the experience.  If you are curious to hear how truly obvious and horrid the difference is, go download some Rammstein videos off Youtube in the various audio formats = AAC, OOG, & Opus =)  Until you add support for native sampling rates, your codec is beyond useless. It is actually a huge step BACKWARD.  The size of the audio portion of videos is so small anyway it may as well be MP3, let alone Opus or AAC.

**Comment by Ultragod** [comment]
Oh by the way, don't play some passive agressive game like pretending U R being fair when judging sounds over a freaking cell phone or something. I'm talking about listening using a real system, OF COURSE!  Many audio chips force resampling anyway, such as every hunk of $hit from the brand 'Realtek', which includes most Apple machines & so on.  If your computer already sounds $hit because it has a bad audio chipset (forced resampling there) then U probably won't notice how ridiculously bad Opus sounds, because EVERYTHING you listen to on that system sounds KRAP =))  Listen to the stuff on a real system with a chipset that maintains native sample rate, & it's a whole other world of awesomeness =D  Realtek should be banned, as should Opus.

**Comment by Ultragod** [comment]
Oh double BTW: If U wanna' go hard core, a couple FREE things U can do is bypass the windows sound mixer by selecting '16 bit intiger' wave out as the sound output format instead of 32 bit float, because float sounds worse.  Also, upsampling (in even multiples) can help, or even re-encoding stuff at a higher bit 'rate', like a 128Kbps AAC re-encoded as 200+BPS MP3 vastly improves the sound. If U want 2 help the world sound better, make an 'on the fly' solution that can plug into MPC-HC or AC3Filter or FFDShow 2 'upconvert' things that way 'on the fly' =)  4 now FFDShow just does sample rates =P  With the right tweaks, & knowing what chipsets R good (I will tell U if U want 2 mail me ~ don't want word spreading making things go up in price) U can get truly high end 'audiophile' results from FREE PCs people leave on the street =)  My fave are a couple particular 'worthless' Dell Models.  The IBM S50 also sound fantastic, though there R some tricks U must do 2 minimize noise.  The S50 R now so 'old' their price has actually gone way UP, so moved on to 'newer' Dell 'junk' 4 my rental fleet =D  Not all Dells, but only certain ones.  balkanguy at live dot com is my addy.  Oh also don't dither.  Things sound clearer if U don't ~ really no downside.

**Comment by Ultragod** [comment]
Oh & in case U were born under a rock, U can download Youtube videos in a variety of formats easily not only via web sites for that purpose, but plugins for Firefox web browser, such as 'Complete Youtube Saver'.  Be sure to DE-select Oprtions\Audio\Audio Options:\(DE-Select) "Mux OPUS audio with DASH WebM video (VP9) when available.  DO select (check box) the "Mux extracted audio..." bla bla and also select "Apply to all video qualities".  That way U get the max sound quality VORBIS (OOG) with your VP9 instead of Opus GARBAGE ruining everything.  VP9 looks more realistic (less jaggy & blocky) than MP4 (H.264) & VP8, even when the VP9 is roughly HALF the size.  I've tested this extensively & it is extremely consistent.  U can lose a bit of minute details when they choose to try and compete for 'tiniest file' that way, but there VP9 handles edges much better so they are not all 'stair-stepped' so much like the others.  I'm guessing they have internal blur & warpsharpening within the codec?  Reminds me of what U get with 'Xsharpen' & 'Warpsharp' via that tool =)  U know what would B useful besides just supporting native sample rates within OPUS is if U guys added a tool kit for FFDShow or within your own thing where people can 'warpsharp and xsharpen' AUDIO to help make things sound more realistic... maybe similar effect to up-converting the 'bit rate' (not just 'depth') of the audio stream.  Between that AND up-sampling (in even multiples) the bit depth, you would really be swingin some heavy hitting awesomeness! =D  I provide SOLUTIONS, and YOU clowns peddle LIES!!  LYING to people claiming 'forcing 48Khz doesn't sound bad' is just a lazy, corrupt $cam 2 twiddle your thumbs instead of fixing your $hit so it stopps sounding like a pile of broken glass.

**Comment by alexchandel** [comment]
Existing OPUS decoders can't follow a 44100 instruction?  If not, adding 44.1 kHz output wouldn't break compatibility.

**Comment by gmaxwell** [comment]
They could not play it, which is exactly what breaking compatibility means. Worse, the quality would almost certainly be *worse* as a result of losing the benefit of the careful tuning of the codec. Not better.  With a good resampler the conversion to 48kHz is essentially lossless, far far more so than the codec itself (technically a matched 44.1>48>44.1 conversion set could be made actually lossless if anyone cared to ever create such a thing).  Opus doesn't do 44.1k because there is literally no point to do so, and supporting different rates makes life harder for decoders (especially ones that have to deal with streams from multiple sources simultaneously).

**Comment by guest271314** [comment]
> Existing OPUS decoders can't follow a 44100 instruction? If not, adding 44.1 kHz output wouldn't break compatibility.

> They could not play it, which is exactly what breaking compatibility means.

What does  `--raw-rate` do?

```
  parec -v --raw -d alsa_output.pci-0000_00_1b.0.analog-stereo.monitor | opusenc --raw-rate 44100 - $HOME/localscripts/output.opus
  mkvmerge -w --enable-durations -o $HOME/localscripts/output.webm $HOME/localscripts/output.opus
```

Firefox 76, Nightly 78, Chromium 81, `mpv`, `ffplay` each play the file.

```
mkvinfo -t output.webm

+ EBML head
|+ EBML version: 1
|+ EBML read version: 1
|+ Maximum EBML ID length: 4
|+ Maximum EBML size length: 8
|+ Document type: webm
|+ Document type version: 4
|+ Document type read version: 1
+ Segment: size 618781
|+ Seek head (subentries will be skipped)
|+ EBML void: size 4029
|+ Segment information
| + Timestamp scale: 22674
| + Multiplexing application: libebml v1.3.10 + libmatroska v1.5.2
| + Writing application: mkvmerge v46.0.0 ('No Deeper Escape') 32-bit
| + Duration: 00:01:00.784753962
| + Date: Wed May 27 03:32:52 2020 UTC
|+ Tracks
| + Track
|  + Track number: 1 (track ID for mkvmerge & mkvextract: 0)
|  + Track UID: 7354171215355932620
|  + Track type: audio
|  + Codec ID: A_OPUS
|  + Seek pre-roll: 00:00:00.080000000
|  + Codec's private data: size 19
|  + Language: und
|  + Codec-inherent delay: 00:00:00.006500000
|  + Audio track
|   + Sampling frequency: 44100
|   + Channels: 2
```

```
$ mkvmerge -J output.opus

{
  "attachments": [],
  "chapters": [],
  "container": {
    "properties": {
      "container_type": 23,
      "is_providing_timestamps": true
    },
    "recognized": true,
    "supported": true,
    "type": "Ogg/OGM"
  },
  "errors": [],
  "file_name": "output.opus",
  "global_tags": [],
  "identification_format_version": 12,
  "track_tags": [],
  "tracks": [
    {
      "codec": "Opus",
      "id": 0,
      "properties": {
        "audio_channels": 2,
        "audio_sampling_frequency": 44100,
        "number": 833194209,
        "tag_encoder": "opusenc from opus-tools 0.1.10"
      },
      "type": "audio"
    }
  ],
  "warnings": []
}
```

```
$ mediainfo output.opus

General
Complete name                            : output.opus
Format                                   : Ogg
File size                                : 560 KiB
Duration                                 : 1 min 0 s
Overall bit rate                         : 75.4 kb/s
Writing application                      : opusenc from opus-tools 0.1.10

Audio
ID                                       : 833194209 (0x31A988E1)
Format                                   : Opus
Duration                                 : 1 min 0 s
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 44.1 kHz
Compression mode                         : Lossy
Writing library                          : libopus 1.1.2
```


```
ffplay output.opus 

[ogg @ 0x9d200600] 693 bytes of comment header remain    0B f=0/0   
Input #0, ogg, from 'output.opus':
  Duration: 00:01:00.78, start: 0.000000, bitrate: 75 kb/s
    Stream #0:0: Audio: opus, 48000 Hz, stereo, fltp
    Metadata:
      ENCODER         : opusenc from opus-tools 0.1.10
```

```
ffprobe output.opus

[ogg @ 0x156b7a0] 693 bytes of comment header remain
Input #0, ogg, from 'output.opus':
  Duration: 00:01:00.78, start: 0.000000, bitrate: 75 kb/s
    Stream #0:0: Audio: opus, 48000 Hz, stereo, fltp
    Metadata:
      ENCODER         : opusenc from opus-tools 0.1.10
```

```
$ mpv output.opus

Playing: output.opus
 (+) Audio --aid=1 (opus 2ch 48000Hz)
AO: [pulse] 48000Hz stereo 2ch float
A: 00:01:00 / 00:01:00 (98%)
```

**Comment by bezdelny** [comment]
Не, ну ёпта, пацаны. Зачем вам 48000 вообще изначально в этом кодеке? Вы делаете его в первую очередь для передачи речи? Тогда так и ответьте автору топика, чтобы музыку свою кодировал во что-то другое, т.к. очередной мега-супер-кодек, который многие эксперты опробовав с помощью своих невероятно чувствительных ушей, указали на его неоспоримое превосходство над другими.
Бро, конвертируй всё в AAC через iTunes и больше не парься ни о чём, всё равно поделия в виде Vorbis и Opus не поддерживаются таким большим перечнем железа, как MP3 и AAC, что требует дополнительных ресурсов для их декодирования.
Удачи.

**Comment by petterreinholdtsen** [comment]
Hi.

Any chance to repeat the request in English?

Few of us can read the original language.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by rillian** [comment]
According to Google's translation service, the Russian comment recommends MPEG codecs as better for music because they are more broadly supported and don't require resampling to/from 44.1 kHz.

**Comment by Doodmanzy** [comment]
Gmaxwell does not care about sound quality, so they pretend that sound quality is irrelevant to everybody =))  Quote: "Opus doesn't do 44.1k because there is literally no point to do so".  = That is an obvious, destructive lie.  Resampling causes aliasing distortion no matter how good the math, leading to more harsh, unnatural sound.  I first noticed this problem with Realtek audio chips on many computers, because the drivers are junk that forces everything to 48Khz rather than locking to native, & also notice the same problem with 'Ensoniq' cards & some others.  Until Opus supports native sample rates of whatever is thrown at it, it is a completely useless codec with no advantages whatsoever.  The larger file sizes of more natural sounding codecs are worth it because they sound so much better.  AAC is terrible because it removes the highs then 'creates fake ones by guessing, creating an odd 'bad 2-way speaker system' kind of sound at lower bit rates, & MP3 does not have that problem & is still the best codec by far, because it is natural at all frequencies until at low bit rates it adds a 'swooshing' chorus type effect, whereas AAC just gets progressively harsh at lower bit rates.  No matter what you do with Opus, because it does not suppor native 44.1 standard 'CD music' sample rate, it will always be useless for quality music reproduction compared to other formats that support native rates.  Any amount of 'sound quality is irrelevant' and 'you can't hear that' comments don't change the fact that it is a problem that most people notice.  When they don't know the exact reason for the problem, they can still tell the difference = smooth vs. harsh, etc.  Opus is a failure until it offers native sample rates, not forcing everything to 48. It's unfortunate, but that's reality, same as AV1 is a decade of work & millions of dollars it seems, but definitely lower quality picture than VP9.  Comparing a 250 megabyte VP9 video to a 200 megabyte AV1, the AV1 looks significantly worse, so what is the point?  Way more CPU time & complexity for a result that is in the end not any more efficient or better looking at the same bit rate, so it's pointless = as pointless as Opus (unless it is modified to support native rates =)  For more details on these facts anybody can reach out to me at 'balkanguy (at) live (dot) com'.  I've worked in 'high end audio' & other such things where sound quality is actually relevant to people =D  Just because YOU do not care does not mean WE don't.  It's better to say something like 'I don't care how it sounds and refuse to fix it'... well then obviously we should not bother dealing with you but people who ARE willing 2 fix it =)  Who is willing to fix the Opus codec so it will support native rates like 44.1Khz?

**Comment by Doodmanzy** [comment]
BTW: Vorbis / OOG is better sounding than Opus (which is harsh resampling nonsense), but worse than AAC or MP3.  For whatever reason, Opus tends 2 collapse the stereo image & sound 'rolled off' =P  AAC tends to be a bit harsh & fake sounding but more 'alive' than Vorbis, & MP3 is still the best overall.  Newer does not necessarily mean better.  Opus is newer & much worse than the others, & AV1 is worse than VP9 = no smaller than VP9 & doesn't look better but takes more CPU overhead = bad choice.  The world would be better off if until those problems are fixed, AV1 & Opus are banned from everything =)

**Comment by joeyhub** [comment]
I see a lot of confusing and misleading information floating around. I get the impression that there is no technical reason not to support 44100 and essentially all the rates seen in MP3. There are however reasons of protocol which is that it has been set as a policy to always generate files that work with existing players. This has some utility but also means that the format is at least partially frozen. It eventually necessitates the need for an opus2. It replaces one compatibility with another. It is possoble there are technical reasons but I do not see them in this thread. I want to raise just one particular point.

I am making two pieces of audio related software. One is scientific and the other is for streamlining audio analysis with marking of specific regions allowing any number of purposes from entertainment to scientific. You can use it to map audio regions to databases, in memory models, make audio sprites, remix, etc. It currently only supports MP3 input and I might not even change that or add much more.

It is programmed by hand with a focus on being reasonably performant yet relatively easy to code with a fair amount of audio. I specifically avoid holding the raw audio data resident in memory. It does not need to be edited with the focus instead on intensive manual but computer aided analysis.

I do a full run through of the raw audio data once in streaming mode to calculate the required data which is a good bit smaller than the raw audio. I would however when a particular track is being played or a part looked as scrutinise the raw data for just that part. The playback library used does not give me the ideal mechanism for this.

MP3 unless I am mistaken can do certain things that make jumping to a particular time even with a good index of the frames problematic. It often appears to have a large delay when seeking in many software players as well as problems calculating the duration in some.

An overview of opus would appear to be a better format to recode to for the in memory copy. The lack of alignment for supporting the same frequency can cause problems. For the scientific use especially. It can tolerate some loss to varying degrees. The resampling however is not ideal where the actual wave is being examined point by point.

There are a number of processes which can be adversely affected by it. It is also not the case that all standard libraries provide a respectable upsampler. It is also adverse to the constraints on the software which are purposeful. It may not save to disk during operation with only in memory content until the final product is produced. It also can only tolerate so much in memory, repeat work and initial load delay. It all adds up and something sometimes must be cut. There are reasons for all of this.

The point here is that there are legitimate use cases for supporting it. If the machine can hear it then you cannot rule out it's utility in software. There are some cases with audio remixing and then applying effects where it will make a difference but I am also not sure that it is even the case that the difference from resampling up is not audible. I suspect on that front it may be a moot point where increasingly more sound systems including OS and sound card run at so therefore upscale to 48000 anyway. In many cases you might find your test was broken.

I also see an issue with this thread of two missing or poorly stated policies. If the format must not create output that with not work with the standard as issued then implemented that is a policy. If the format is mad for the typical human ear then that is a policy. That is not unusual in software development. These both establish scope and strategy. It is just not stated as clearly as it could be.
