### ISSUE TITLE
Array subscript is above array bounds when compiling NLSF2A.c

### ISSUE THREAD

**Issue by coltongit** [xiph/opus#7]
I happened to come across this bug with spearmint, available at spearmint.pw. The description of this bug is, when you go to compile opus, the compiler gives out 4 warnings. Here's an excerpt of the warning as it happens:
```
CC code/opus-1.1/silk/NLSF2A.c
code/opus-1.1/silk/NLSF2A.c: In function ‘silk_NLSF2A’:
code/opus-1.1/silk/NLSF2A.c:121:17: warning: array subscript is above array bounds [-Warray-bounds]
Ptmp = P[ k+1 ] + P[ k ];
^
code/opus-1.1/silk/NLSF2A.c:122:17: warning: array subscript is above array bounds [-Warray-bounds]
Qtmp = Q[ k+1 ] - Q[ k ];
^
code/opus-1.1/silk/NLSF2A.c:121:17: warning: array subscript is above array bounds [-Warray-bounds]
Ptmp = P[ k+1 ] + P[ k ];
^
code/opus-1.1/silk/NLSF2A.c:122:17: warning: array subscript is above array bounds [-Warray-bounds]
Qtmp = Q[ k+1 ] - Q[ k ];
^
```
This also happens when compiling any project which uses opus, meaning it's probably also a bug with opus.

**Comment by rillian** [comment]
I think these are spurious. On line 89 we have

```silk_assert( d==10||d==16 );```

then on line 113, the loop bound is set to

```dd = silk_RSHIFT( d, 1 );```

so `dd` is either 5 or 8. Meanwhile the array itself is size `SILK_MAX_ORDER_LPC / 2 + 1` which is 9 (by SigProc_FIX.h:38) so the `k+1` array access is safe.

Any suggestions how we can silence the warning? Which compiler version shows the issue?

**Comment by coltongit** [comment]
Latest Cygwin, rillian. I'm currently using the x64 version.

**Comment by rillian** [comment]
what does `gcc --version` say?

**Comment by coltongit** [comment]
It reports gcc 5.3.0.

**Comment by coltongit** [comment]
zturtleman fixed this error. I plan to pull request the new file.

**Comment by rillian** [comment]
Thanks for the link. I'd rather not just turn the warning off, since it can find real bugs elsewhere.

Oddly, I can't reproduce with gcc 5.3 or 6.1 on linux, nor with cross-mingw32-gcc 6.1 on linux with the opus autotools build, and not with gcc 6.0 on linux with the spearmint build (although I do see array-bounds warnings for several other spearmint submodules). I also don't see any differences between the silk code in the opus master branch verses the spearmint fork which would change the array bound calculation.

**Comment by coltongit** [comment]
He reverted the changes explained here because it broke compilation on Mac OS X 10.6.8.
