### ISSUE TITLE
Quality issue with 'synthesized' (encoded) Ambisonic sound fields 

### ISSUE THREAD

**Issue by mgorzel** [xiph/opus#95]
Currently, for Ambisonics (channel mapping family 2) [opus multistream encoder](https://github.com/xiph/opus/blob/master/src/opus_multistream_encoder.c#L736) allocates more bits to the omnidirectional sound field component (channel 1) as compared to directional channels.

This optimization works well with captured (more 'diffuse') sound fields. However, it leads to strong quality artifacts when a sound field is synthesized (e.g. manually encoded from mono audio(s)), especially when the sound source is panned left/right. This is well illustrated by the attached 'noise_opus_256kbps_stereo.wav' example from [sound_examples.zip](https://github.com/xiph/opus/files/2336026/sound_examples.zip) where a single broadband sound source is panned from left to right (rendered from Ambisonics to stereo using M-S matrixing).

To mitigate this problem, since omni- and directional channels may end up having a highly correlated content, equal bit allocation should work better (please compare with the 'noise_opus_eq_256kbps_stereo.wav' example in [sound_examples.zip](https://github.com/xiph/opus/files/2336026/sound_examples.zip)).

Also, equal bit allocation seems to work well with a variety of audio content I've tested (recorded and synthesized). In the attached folder you can also find an example of an Ambisonic recording for comparison (recorded using Eigenmike - [source](https://mhacoustics.com/sites/default/files/solo_guitar.wav)).

**Comment by jmvalin** [comment]
I think in the end it likely has more to do with the relative energy of the omni vs directional channels. Since omni generally has more energy it's allocated a higher bitrate, but this could also be adaptive (just like for surround). Since I do not have a setup that allows me to properly test ambisonics encoding, it's a bit hard for me to be of more help. Maybe you should raise the issue on the mailing list and discuss with the Google people who wrote the ambisonics patches.

**Comment by jmvalin** [comment]
Sorry, had not realized you were with Google. For these kinds of issues, I would simply suggest having Felicia review your patch, since she's in a better position to evaluate it (and she's got commit access). It seems to me like the long-term solution is to do something similar to what we do for surround (masking-based bitrate), but in the short-term, this kind of change is probably fine. Giving omni a few more bits still seems like a reasonable thing to do, but I'll still leave it up to Felicia.

**Comment by felicialim** [comment]
The tests that @mgorzel ran indeed show that this simple bitrate allocation change works well for now for a range of signals so I've committed the patch. Thanks for also looking at it, @jmvalin!

**Comment by jmvalin** [comment]
Actually, I had not reviewed the patch and was leaving that to you. But having a quick look at it, it seems like the allocation is divided evenly per stream, whereas it should probably be divided evenly per channel. IIRC the ambisonics channels are uncoupled, but the (stereo) non-diegetic stream is going to be starved if the allocation is per stream.

**Comment by felicialim** [comment]
Yes, that does look unintuitive; Marcin had also tested splitting the bitrates evenly per channel and found that the (uncoupled) ambisonics channels tended to require higher bitrates to avoid artifacts, but we could get away with lower bitrates for each of the stereo non-diegetic.

**Comment by jmvalin** [comment]
You can always look at what surround does. Basically, each stream gets a fixed number of bits up-front (offset), and from there each channel gets its share of what's left. That makes for a gradual change from per-stream allocation (at low bitrate) to per-channel allocation (at high bitrate).

**Comment by felicialim** [comment]
That makes sense, and would be interesting to try too. Thanks!

**Comment by jmvalin** [comment]
OK, I think this got resolved so I'm closing it (feel free to reopen if I missed something)
